### ISSUE TITLE
ResponsiveLabel not updating correctly in UITableView

### ISSUE THREAD

**Issue by David-Molloy** [hsusmita/ResponsiveLabel#10]
I have a UITableViewCell in which I am using two separate ResponsiveLabel. When I scroll through the table the ResponsiveLabel is repeating text from pervious cells. I have checked that the text being set in the fields was the correct text. My logging appears to show that this is not the problem. I then started looking at where the various draw methods are being called, and this leads me to believe that the issue is with the ResponsiveLabel. It appears that even though the text is being correctly set from the model, the ResponsiveLabel’s draw method is being called before the text is set in the ResponsiveLabel. My logging is currently showing that the ResponsiveLabel’s text is often null when the cell is being draw.
Using the current version of ResponsiveLabel 1.0.5

**Comment by hsusmita** [comment]
@David-Molloy I tried to simulate your condition. It seems to work fine. Can you provide me with more info?May be some sample example will help.

**Comment by David-Molloy** [comment]
Hi

found out the problem, the ResponsiveLabel does not clear the textstorage
if you set the ResponsiveLabel to nil. We are using the ResponsiveLabel in
a tableviewcell. Not every cell will display text, so when the cell gets
reused it still has the text from a pervious cell that did use the
ResponsiveLabel. At the start of each CellForRowAtIndexPath we where
setting the ResponsiveLabel to nil but in the updateTextStorage there is a
check to see if the length of the string is greater than zero and only then
update the textstorage.
This would be a simple fix, to allow to clear the ResponsiveLabel.

- (void)clearText

{

    NSMutableAttributedString *emptyString = [[NSMutableAttributedString
alloc] initWithString:@""];

    [super setText:@""];

    [super setAttributedText:emptyString];

    self.attributedText = emptyString;

    self.text=@"";

    [self.textStorage setAttributedString:emptyString];

}

**Comment by hsusmita** [comment]
Great work @David-Molloy. Thank you for digging into the issue. I will update is soon.

**Comment by hsusmita** [comment]
@David-Molloy Instead of creating a separate method, I have added code to handle nil string. You can check the version 1.0.6.
