### ISSUE TITLE
Request: highlighted background rect rounded

### ISSUE THREAD

**Issue by andr3a88** [hsusmita/ResponsiveLabel#11]
Hi, it is possible to make the highlighted rect with rounded corners?

![schermata 2015-08-27 alle 12 49 08](https://cloud.githubusercontent.com/assets/6755254/9518806/3297d5c2-4cba-11e5-8c18-8424e0751a5e.png)

**Comment by hsusmita** [comment]
@andr3a88 As per current implementation it is not possible to do so. When a text is tapped, NSBackgroundColorAttributeName attribute is updated. to achieve this goal, the following method needs to be overriden with custom drawing code.
- (void)drawBackgroundForGlyphRange:(NSRange)glyphsToShow atPoint:(CGPoint)origin

I will research about this and try to implement. If you can come up with custom drawing code for the same, you can push to the repo and create a pull request.

**Comment by hsusmita** [comment]
@andr3a88 I have implemented the feature. I have pushed code in develop branch. Can you have a look whether it works as expected? It would be great if you have any suggestion about performance.

**Comment by heistings** [comment]
@hsusmita I am working around with a UITextView, and I want to do almost the thing as you. Thanks for your demonstration
