### ISSUE TITLE
hightlightedTextColor = nil results in crash

### ISSUE THREAD

**Issue by MartijnSchoemaker** [hsusmita/ResponsiveLabel#14]
It's possibe that hightlightedTextColor = nil on line 712 of responsiveLabel.m

  else if (self.isHighlighted)
    colour = self.highlightedTextColor;

This results (sometimes) in a crash on line 719.

Solution proposal:
  else if (self.isHighlighted && self.highlightedTextColor)
    colour = self.highlightedTextColor;

**Comment by hsusmita** [comment]
@MartijnSchoemaker Done!
