### ISSUE TITLE
Crash in ResponsiveLabel.m line 335

### ISSUE THREAD

**Issue by nick3389** [hsusmita/ResponsiveLabel#17]
@hsusmita  Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'

Can you check it out?

**Comment by hsusmita** [comment]
@nick3389 Is it in bigfixes branch or master branch?

**Comment by nick3389** [comment]
bugfixes branch. The one i downloaded yesterday

**Comment by nick3389** [comment]
@hsusmita spicifically in this line:

[self.textStorage removeAttribute:key range:self.truncatedPatternRange];

**Comment by hsusmita** [comment]
@nick3389 Does your text has new line character?

**Comment by nick3389** [comment]
@hsusmita the text is from a user's input in a UITextView. so maybe the user hit the the return button. Do you have any idea why this is happening?

**Comment by hsusmita** [comment]
The reason either self.truncatedPatternRange has garbage value or the calculated range is out of bounds. Tell me value of truncatedPatternRange when the crash occurs.

**Comment by nick3389** [comment]
@hsusmita Sometimes i see this in the debugger:

tokenRange	NSRange	location=9223372036854775807, length=0 (I don't know if it's relevant)

truncatedPatternRange when the crash occurs
truncated range   129  7

**Comment by hsusmita** [comment]
Can you track the user input? I have identified the offending code. I want to make sure if this is because of new line character.

**Comment by nick3389** [comment]
imagine that this is a comment that the user made on a product. The user writes the comment, hits save and this is stored in the database. Then I have an http call to retrieve the comments and i have a tableview to display them. What do you want me to do?

**Comment by hsusmita** [comment]
At the point of crash, can u print the attributedText of ResponsiveLabel?

**Comment by nick3389** [comment]
It's in greek. Do you still want it?

**Comment by hsusmita** [comment]
yes!

**Comment by nick3389** [comment]
Comment:   Αποξηραμένες ντομάτες σε παρθένο ελαιόλαδο, ιδανικές για κάθε μεζέ, για πέστο φέτας και για εντονότερη γεύση στα μαγειρευτά σας! #tomato #kalamata #sundried 
 (there is always a space at the end because you do not catch the hashtag)

Range: 129  7

**Comment by hsusmita** [comment]
Have you enabled custom truncation?

**Comment by nick3389** [comment]
@hsusmita  i suppose no...

**Comment by hsusmita** [comment]
What is the value of self.customTruncationEnabled? So there is reuse of table view cell in your case?

**Comment by nick3389** [comment]
@hsusmita Yes that's right. I enabled it now.

**Comment by hsusmita** [comment]
value of self.truncatedPatternRange?

**Comment by nick3389** [comment]
Always (0,0) now

**Comment by hsusmita** [comment]
@nick3389 I could not reproduce the bug. However I added some checks. Check code present in bugfixes branch and let's see how it goes.

**Comment by nick3389** [comment]
With customTruncationEnabled = YES in the label, i haven't noticed the bug yet. I just replaced the new code and I will test again. Again, many thanx!

**Comment by nick3389** [comment]
@hsusmita  'NSRangeException', reason: 'NSConcreteMutableAttributedString attributedSubstringFromRange:: Out of bounds'

new crash today. i ma trying to identify where is it but i guess it's in the same file

**Comment by nick3389** [comment]
@hsusmita  this is the visible string that i log:

@"Παστελαριές της Αθανασίας που ακολουθεί τα βήματα της παράδοσης στην Ανδρο.\n #παστελαριές #γλυκ"

As you see it indeed contains a new line character, as you told me yesterday. I fixed it temporary with:

hashtagString = [hashtagString stringByReplacingOccurrencesOfString:@"\n" withString:@" "];

**Comment by hsusmita** [comment]
@nick3389 Hey I have added some fixes to prevent crash. Can you check "bugfixes" branch and let me know if the issue with newline character is fixed?
