### ISSUE TITLE
Crash while scrolling: index (X) beyond array bounds (X)

### ISSUE THREAD

**Issue by ivanviragine** [hsusmita/ResponsiveLabel#21]
Hi!

I'm getting some random crashes when using a ResponsiveLabel inside a xib from a TableView.
When first displayed on the TableView, it goes ok, but when I scroll down, see the next row, and then scroll back to the first row, it crashes.
This happens only when the text is close to the edge of the label, for example (the pipes | denotes labels' bounds):

| this is a text @text           | < fine
| this is a text that @crashs | < not ok

Here's the log:

2015-10-03 10:05:33.926 App[2063:57122] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** NSRunStorage, _NSBlockNumberForIndex(): index (80) beyond array bounds (80)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c57df65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010bbd8deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c57de9d +[NSException raise:format:] + 205
	3   UIFoundation                        0x00000001155ce94b _NSBlockNumberForIndex + 84
	4   UIFoundation                        0x000000011558c369 -[NSLayoutManager(NSPrivate) _invalidateGlyphsForExtendedCharacterRange:changeInLength:includeBlocks:] + 703
	5   UIFoundation                        0x0000000115580695 -[NSLayoutManager(NSPrivate) _fillLayoutHoleForCharacterRange:desiredNumberOfLines:isSoft:] + 1030
	6   UIFoundation                        0x0000000115582104 -[NSLayoutManager(NSPrivate) _fillLayoutHoleAtIndex:desiredNumberOfLines:] + 201
	7   UIFoundation                        0x0000000115582787 -[NSLayoutManager(NSPrivate) _markSelfAsDirtyForBackgroundLayout:] + 339
	8   UIFoundation                        0x000000011558ced7 -[NSLayoutManager(NSPrivate) _invalidateLayoutForExtendedCharacterRange:isSoft:invalidateUsage:] + 2106
	9   UIFoundation                        0x00000001155bcfea -[NSLayoutManager textStorage:edited:range:changeInLength:invalidatedRange:] + 219
	10  UIFoundation                        0x00000001155bd2d2 -[NSLayoutManager processEditingForTextStorage:edited:range:changeInLength:invalidatedRange:] + 47
	11  UIFoundation                        0x00000001155e4a76 -[NSTextStorage _notifyEdited:range:changeInLength:invalidatedRange:] + 152
	12  UIFoundation                        0x00000001155e4591 -[NSTextStorage processEditing] + 349
	13  UIFoundation                        0x00000001155e41eb -[NSTextStorage endEditing] + 82
	14  Foundation                          0x000000010a33b10d -[NSMutableAttributedString addAttributes:range:] + 321
	15  UIFoundation                        0x00000001155e69c4 __45-[NSConcreteTextStorage addAttributes:range:]_block_invoke + 267
	16  UIFoundation                        0x00000001155e682e -[NSConcreteTextStorage addAttributes:range:] + 109
	17  App                                 0x000000010889803f __53-[ResponsiveLabel addAttributesForPatternDescriptor:]_block_invoke + 799
	18  CoreFoundation                      0x000000010c4bfd7d __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 77
	19  CoreFoundation                      0x000000010c4bfc26 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 166
	20  App                                 0x0000000108897cc7 -[ResponsiveLabel addAttributesForPatternDescriptor:] + 311
	21  App                                 0x00000001088997a5 __37-[ResponsiveLabel updateTextStorage:]_block_invoke + 133
	22  CoreFoundation                      0x000000010c4b6466 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	23  CoreFoundation                      0x000000010c4b635a -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 202
	24  App                                 0x00000001088996dc -[ResponsiveLabel updateTextStorage:] + 476
	25  App                                 0x00000001088933e3 -[ResponsiveLabel setText:] + 275
	26  App                                 0x00000001087fbb7a -[FeedMainViewController tableView:cellForRowAtIndexPath:] + 1290
	27  UIKit                               0x000000010a8b06b3 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 782
	28  UIKit                               0x000000010a8b07c8 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
	29  UIKit                               0x000000010a886589 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2988
	30  UIKit                               0x000000010a8b9595 -[UITableView _performWithCachedTraitCollection:] + 92
	31  UIKit                               0x000000010a8a19ad -[UITableView layoutSubviews] + 218
	32  UIKit                               0x000000010a81211c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
	33  QuartzCore                          0x000000010918d36a -[CALayer layoutSublayers] + 146
	34  QuartzCore                          0x0000000109181bd0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	35  QuartzCore                          0x0000000109181a4e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	36  QuartzCore                          0x00000001091761d5 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	37  QuartzCore                          0x00000001091a39f0 _ZN2CA11Transaction6commitEv + 508
	38  QuartzCore                          0x00000001091b27cc _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 576
	39  CoreFoundation                      0x000000010c4de364 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	40  CoreFoundation                      0x000000010c4ddf11 __CFRunLoopDoTimer + 1089
	41  CoreFoundation                      0x000000010c49f8b1 __CFRunLoopRun + 1937
	42  CoreFoundation                      0x000000010c49ee98 CFRunLoopRunSpecific + 488
	43  GraphicsServices                    0x000000010da14ad2 GSEventRunModal + 161
	44  UIKit                               0x000000010a761676 UIApplicationMain + 171
	45  App                                 0x00000001088a249f main + 111
	46  libdyld.dylib                       0x0000000110bf992d start + 1
	47  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by ivanviragine** [comment]
Adding a new discover:

This happens ONLY if there's an blank space after the @ text.

Here's an example of text:

**Vendo o movimento com minha irmã @gigi**


**Watching the movement with my sis @gigi**

Goes ok.
But when adding space after the first @gigi, like this

**Vendo o movimento com minha irmã @gigi **


**Watching the movement with my sis @gigi**

It crashes!

**Comment by hsusmita** [comment]
@ivanviragine Which version are you using?

**Comment by ivanviragine** [comment]
Latest from zip.

--

**Comment by hsusmita** [comment]
@ivanviragine cool! I will have a look and update you by Monday.

**Comment by ivanviragine** [comment]
Thanks a lot!

--

**Comment by hsusmita** [comment]
In case you are using 1.0.5, can you check with 1.0.8?

**Comment by ivanviragine** [comment]
Hi!

I'm using 1.0.8. Downloaded the zip yesterday, just to be really sure!


Atenciosamente,

--
Ivan Nicola Viragine

**Comment by hsusmita** [comment]
@ivanviragine I am not able to reproduce. Can you prepare an sample project with your data set so that I can dig into this?

**Comment by ivanviragine** [comment]
Thanks!

I'll try to make this sample.
Just as a tip: it doesn't happen on iPhone 6, for example, happens on
iPhone 5.
If you want to reproduce the problem, your text has to reach the right
corner of the screen... the same code on iPhone 6 had room on the right
side, so it worked fine, on iPhone 5 the text was over the edge.


Atenciosamente,

--
Ivan Nicola Viragine

**Comment by ivanviragine** [comment]
@hsusmita any news on this?

I've tried to pull a simplified version of my app, but it's not simple.
I'll try again soon...
