### ISSUE TITLE
Add expanded state end token 

### ISSUE THREAD

**Issue by luctek** [hsusmita/ResponsiveLabel#22]
Hi,

Here is the use case I would like to be able to achieve with the label. Have the "More" label (TruncationToken) to expand the view and a "... Less" label at the end of the text when the view is expanded and want to revert to the collapsed view. 

Setting the setAttributedTruncationToken of the label after it has expanded doesn't display the "... Less" label since it's not truncated anymore.

Could you provide functionality to accomplish this? 

Thank you very much for your help.

**Comment by hsusmita** [comment]
@luctek This use case is very specific. The purpose of this library is to function like UILabel with enhanced features. The repository has an example which implements expanding and collapsing text. Here is the sample code.

```
NSString *str = self.customLabel.text;
NSString *kCollapseToken = @"...Less";
 NSString *expandedString = [NSString stringWithFormat:@"%@%@",str,kCollapseToken];
    finalString = [[NSMutableAttributedString alloc]initWithString:expandedString attributes:@{NSForegroundColorAttributeName:[UIColor blackColor]}];
    PatternTapResponder tap = ^(NSString *string) {
      //Code to collapse the view
    };
    [finalString addAttributes:@{NSForegroundColorAttributeName:[UIColor blueColor],RLTapResponderAttributeName:tap}
                         range:[expandedString rangeOfString:kCollapseToken]];
    [finalString addAttributes:@{NSFontAttributeName:self.customLabel.font} range:NSMakeRange(0, finalString.length)];
```
