### ISSUE TITLE
How to change the default Black Color of ResponsiveLabel.

### ISSUE THREAD

**Issue by CGTRahul** [hsusmita/ResponsiveLabel#23]
How can I change the default Black color of ResponsiveLabel. I've tried setting the White color through the Attributes Inspector as well as through code but it still shows the default black color.

**Comment by georgesteiner** [comment]
I have not had trouble changing the color in the attributes inspector, were you able to figure out what was wrong?

**Comment by CGTRahul** [comment]
Not yet. I dropped the plan of using the ResponsiveLabel library.
