### ISSUE TITLE
Doesn't respect numberOfLines property?

### ISSUE THREAD

**Issue by kidsid49** [hsusmita/ResponsiveLabel#24]
So my label.numberOfLines = 4. So it always draw a big UILabel rect even if text is just one line. 
No matters how small a text is it always consider its a big as  provided in numberOfLines.

**Comment by georgesteiner** [comment]
yes I have noticed this too

**Comment by georgesteiner** [comment]
here is a simple work around I just came up with that seems to do the trick for me, hope this helps!

//figure out what you want the max width and heigh to be for your label
CGSize boundingSize = CGSizeMake(maxWidthForLabel, maxHeightForLabel); 

//draw your label and figure out how tall it will need to be given it's text and font attributes
CGRect textRect = [textForLabel boundingRectWithSize:boundingSize options:NSStringDrawingUsesLineFragmentOrigin attributes: @{NSFontAttributeName : self.label.font} context:nil];

//convert to integers
textRect.size.width = ceil(textRect2.size.width);
textRect.size.height = ceil(textRect2.size.height);

//determine how tall each line of text is based on your font attributes, for me it was 18 and I have my numberOfLInes set to 3 by default so I handled the scenarios where it's 1 or 2 lines    
if (textRect.size.height == 36) {
        self.dishInfoString.numberOfLines = 2;
}
    
if (textRect.size.height == 18) {
        self.dishInfoString.numberOfLines = 1;
}

**Comment by kidsid49** [comment]
Not helping much :-(

**Comment by kidsid49** [comment]
I did this in my case maximum number of lines was 4.

    CGSize requiredSize = [storyCell.showReviewLabel.text boundingRectWithSize:CGSizeMake(CGRectGetWidth(storyCell.showReviewLabel.frame), CGFLOAT_MAX) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{NSFontAttributeName:storyCell.showReviewLabel.font} context:nil].size;
    
    CGFloat charSize = storyCell.showReviewLabel.font.lineHeight;
    CGFloat rHeight = requiredSize.height;
    NSUInteger numberOfLines = ceil(rHeight/charSize);
    if(numberOfLines < 4) {
        storyCell.showReviewLabel.numberOfLines = numberOfLines;
    } else {
        storyCell.showReviewLabel.numberOfLines = 4;
    }
