### ISSUE TITLE
Highlighted color for pattern

### ISSUE THREAD

**Issue by andr3a88** [hsusmita/ResponsiveLabel#3]
Hi, is possible to configure  background color for a pattern when the user touch on it?

**Comment by susmita-fueled** [comment]
@andr3a88 Currently this feature is not available. Please add one github issue. I will implement it as earliest as possible.

**Comment by hsusmita** [comment]
@andr3a88 You can try latest version of ResponsiveLabel for this feature.

**Comment by andr3a88** [comment]
Thank you!
