### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Ying1986** [hsusmita/ResponsiveLabel#31]
@hsusmita 
I have found crash issue while use this control.

http://crashes.to/s/2923ed77506/details

Please check and fix it.
Thank you,

![resposivelable](https://cloud.githubusercontent.com/assets/6648212/12592662/16a862bc-c476-11e5-9edb-c6995310ef2c.PNG)

**Comment by hsusmita** [comment]
@Ying1986 Can you provide me with some test cases for which it is crashing?
