### ISSUE TITLE
Change the font for the first match 

### ISSUE THREAD

**Issue by CavalcanteLeo** [hsusmita/ResponsiveLabel#34]
I'm facing a problem when the sentece has same words.
eg:
Username "a"
sentence: "a": i have "a" dream
i'd change the font for only the fist "a".

Does anyone knows how to do that?

**Comment by hsusmita** [comment]
@CavalcanteLeo 
You can use NSAttributedString for that.
`let finalString = NSMutableAttributedString(string: "\"a\": i have \"a\" dream")
finalString.addAttribute(NSFontAttributeName, value: UIFont.systemFontOfSize(15.0), range: NSMakeRange(0,1))
`

**Comment by hsusmita** [comment]
@CavalcanteLeo Try this one
```
NSString *pattern = [NSString stringWithFormat:@"%s","\"a\""];
	NSRegularExpression *expression = [[NSRegularExpression alloc]initWithPattern:pattern options:NSRegularExpressionCaseInsensitive error:nil];
	PatternDescriptor *descriptor = [[PatternDescriptor alloc]initWithRegex:expression
															 withSearchType:PatternSearchTypeFirst withPatternAttributes:
									 @{ NSFontAttributeName: [UIFont systemFontOfSize:15.0], NSForegroundColorAttributeName: [UIColor redColor]}];
	[self.responsiveLabel enablePatternDetection:descriptor];

```

**Comment by CavalcanteLeo** [comment]
worked, thank you!!
