### ISSUE TITLE
Zero Label view size

### ISSUE THREAD

**Issue by romanvbabenko** [hsusmita/ResponsiveLabel#4]
I have only parent ViewController(not TableViewCell) and a Label with associated ResponsiveLabel custom class.
In runtime I cannot see the label, 'cos it's zero heigh and width. Is it a feature or a bug? How can I fix this?

**Comment by hsusmita** [comment]
@romanvbabenko , is it showing error on console that it's height and width are zero? Does this work fine if you use UILabel?

**Comment by romanvbabenko** [comment]
No, it's ok if use UILabel. It happens when I use ResponsiveLable which is laying on ViewController and I inspect it via Calabash query "label all" I get 

[2] {
                          "id" => nil,
                 "description" => "<ResponsiveLabel: 0x7fbcd1e836a0; baseClass = UILabel; frame = (34 159; 0 0); text = 'I love #Ruby and #Objctiv...'; opaque = NO; autoresize = RM+BM; layer = <_UILabelLayer: 0x7fbcd1e839d0>>",
                       "label" => "I love #Ruby and #Objctive-C",
                       "frame" => {
                 "y" => 159,
                 "x" => 34,
             "width" => 0,
            "height" => 0
        },
        "accessibilityElement" => true,
                       "value" => "I love #Ruby and #Objctive-C",
                       "alpha" => 1,
                     "enabled" => true,
                     "visible" => 1,
                        "text" => "I love #Ruby and #Objctive-C",
                       "class" => "ResponsiveLabel",
                        "rect" => {
                   "y" => 159,
            "center_x" => 34,
            "center_y" => 159,
                   "x" => 34,
               "width" => 0,
              "height" => 0
        }
    },

So as you can see the label is present, but invisible, 'cos it's zero size.

**Comment by hsusmita** [comment]
@romanvbabenko Thanks for pointing this. It is a bug. Basically, when you instantiate ResponsiveLabel from storyboard, the initial text set via storyboard is not getting set. That is why the width and height are set to zero. I will fix it soon.

**Comment by hsusmita** [comment]
@romanvbabenko  For temporary fix, try setting text programmatically.

**Comment by romanvbabenko** [comment]
I see, I'll. That's the reason why it worked for me in TableView, 'cos I'd configured cell programmatically.
Ok. Looking forward to updated and if you'd have time and inspiration to help me with second part of this issue: how can I simulate touches of ResponsiveLabel objects(hashes, handles, etc) via Calabash API. Let me know if you have any ideas, 'cos your knowledge of ResponsiveLabel author more deeper than mine.

**Comment by hsusmita** [comment]
@romanvbabenko I have updated ResponsiveLabel. Now it can take up size defined in the storyboard.
