### ISSUE TITLE
Pattern Attributes not applied when the label size more than the content height

### ISSUE THREAD

**Issue by hsusmita** [hsusmita/ResponsiveLabel#7]

**Comment by nick3389** [comment]
I have the following problem. When the text of the label is small or significant smaller than the label's height the patterns do not work. Do you have any suggestion? Thanx.

**Comment by hsusmita** [comment]
@nick3389 can you tell me the font size and label height?
The patterns would not work when content height calculation is not accurate. Need more information to dig into the issue.

**Comment by nick3389** [comment]
Label's height: 325, Label's width: 247, font: 13 and the text is about 3 lines.

**Comment by hsusmita** [comment]
@nick3389 Do you have problem in applying pattern or problem in highlighting the pattern while tapping?

**Comment by nick3389** [comment]
@hsusmita The problem is in applying the pattern. It is highlighted but i tap it and nothing happens.

**Comment by hsusmita** [comment]
Can you post the attributes added for the pattern?

**Comment by nick3389** [comment]
PatternTapResponder hashTagTapAction = ^(NSString *tappedString) {
NSLog(@"hashtag tapped");     
};
[self.commentText enableHashTagDetectionWithAttributes:@{NSForegroundColorAttributeName: [UIColor colorWithRed:0.0 green:180.0/255.0 blue:241.0/255.0 alpha:1.0], RLTapResponderAttributeName: hashTagTapAction}];

**Comment by hsusmita** [comment]
Ok I got it. So NSForegroundColorAttributeName is applied, but while tapping, the action does not fire. right?

**Comment by nick3389** [comment]
Yes, that's right.

**Comment by hsusmita** [comment]
Thanks for your input. I found the problem. I will update it soon.

**Comment by nick3389** [comment]
ok. Post here if you can to check it immediately.

**Comment by hsusmita** [comment]
@nick3389 Please check out the branch bugfixes, run your tests and let me know if that works.

**Comment by nick3389** [comment]
@hsusmita Yes it is ok now. Many thanx!. Also, I have noticed two bugs:
1) the adjustsFontSizeToFitWidth property is not working
2) if there are two consecutive hashtags, you do not catch the second one. Generally, you catch only the first. Example: #test1#test2#test3. You catch and highlight only #test1, not the other two.

**Comment by hsusmita** [comment]
@nick3389 Thanks for pointing these issues. For point 2, I am looking for appropriate regular expression. If you construct one which can distinguish two consecutive patterns, then let me know.
