### ISSUE TITLE
IB Designables error on storyboard

### ISSUE THREAD

**Issue by andr3a88** [hsusmita/ResponsiveLabel#8]
Since I've updated to the last version on cocoapods I've these two errors on the storyboard:

![schermata 2015-08-03 alle 14 35 16](https://cloud.githubusercontent.com/assets/6755254/9037579/fb20afa4-39ec-11e5-94fe-821f33b3376a.png)

**Comment by hsusmita** [comment]
@andr3a88 Can you confirm me your deployment target?

**Comment by andr3a88** [comment]
@hsusmita From iOS 7.0. To fix the errors for now, I commented the IB_DESIGNABLE and IBInspectable on ResponsiveLabel.h

**Comment by hsusmita** [comment]
@andr3a88 That makes sense. IB_DESIGNABLE and IBInspectable were introduced in iOS 8. I'll see if I can make this feature optional depending on the version.

**Comment by andr3a88** [comment]
@hsusmita After a "pod update" I have this warning by cocoapods, may be related to the deployment target on the podfile ( platform :ios, "7.0")
![schermata 2015-08-03 alle 17 23 24](https://cloud.githubusercontent.com/assets/6755254/9040765/774de990-3a04-11e5-96f8-abcec598ed0f.png)

**Comment by hsusmita** [comment]
@andr3a88 I have added code for conditional compilation, i.e the code for IB_DESIGNABLE and IBInspectable will be compiled if the target is greater than 8.0. Unfortunately I am unable to test this. I am using XCode 6.4. I don't get any compilation error. Can you check out branch bugfixes and test at you end?

**Comment by andr3a88** [comment]
now looks all right
