### ISSUE TITLE
Truncation token set from interface builder does not show

### ISSUE THREAD

**Issue by Mackarous** [hsusmita/ResponsiveLabel#9]
I am trying to set the truncation token in IB, but I do not have width/height constraints. I have top, bottom, left, right constraints instead. The UILabel is set to be a ResponsiveLabel, number of lines = 0.

The token shows in IB, but not when the app runs

Any ideas?

**Comment by hsusmita** [comment]
@Mackarous Have you given preferred width?

**Comment by hsusmita** [comment]
@Mackarous I figured out the issue. I need some more time to fix this. For the time being, you can programmatically set the truncation token.

**Comment by Mackarous** [comment]
@hsusmita I have a preferred width, and I attempted to set the truncation token programatically also but it still doesn't work.

**Comment by hsusmita** [comment]
@Mackarous Does it show default ellipse?

**Comment by Mackarous** [comment]
Yes it does

**Comment by hsusmita** [comment]
@Mackarous Is there any error regarding IBDesignable?

**Comment by Mackarous** [comment]
No error for IBDesignable at all

**Comment by hsusmita** [comment]
@Mackarous, I am unable to diagnose the issue. It should work programmatically. Can you share sample code on github? It would be helpful in understanding the issue.

**Comment by Mackarous** [comment]
Sure. I simply add a label to my storyboard. The label has top, bottom, left, and right constraints. No height or width constraints. It has numberOfLines = 5, and I add too much text so it must truncate. I then use the following lines of code:

```
let token = "... More"
let attributedString = NSMutableAttributedString(string: self.label.text, attributes: [NSFontAttributeName : self.label.font])
self.label.setAttributedTruncationToken(attributedString, withAction: { tappedString in
    println("hit")
})
self.label.setText(self.labelText, withTruncation: true)
```

**Comment by hsusmita** [comment]
@Mackarous Updated library. Try latest version, i.e 1.0.4 and let me know if there is still any issue.
FYI, I will be releasing swift implementation of ResponsiveLabel by the end of this week.

**Comment by Mackarous** [comment]
@hsusmita Thank you! It works perfectly now! Great work. Also just wondering if you are planning on putting hit state on the truncation token?

**Comment by hsusmita** [comment]
@Mackarous What do you mean by hit state? Is it something like highlighting the token on tap?

**Comment by Mackarous** [comment]
@hsusmita yes exactly

**Comment by hsusmita** [comment]
@Mackarous The bug in highlighting token is fixed. Check the version 1.0.5. Here is the sample code is 
```
    let token = "... Read More"
    let attributedString = NSMutableAttributedString(string: token, attributes: [NSFontAttributeName : self.label.font
   ,RLHighlightedBackgroundColorAttributeName:UIColor.blackColor(),RLHighlightedForegroundColorAttributeName:UIColor.greenColor(),NSForegroundColorAttributeName:UIColor.redColor()])
    
    self.label.setAttributedTruncationToken(attributedString, withAction: { tappedString in
      println("hit")
    })
   
self.label.setText(self.labelText, withTruncation: true)
```

**Comment by Mackarous** [comment]
Perfect! Thank you so much!
